services:
  quizapp.api:
    image: ${DOCKER_REGISTRY-}quizappapi
    container_name: Quiz.Api
    build:
      context: .
      dockerfile: API/QuizApp.API/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081

  quiz.database:
    image: postgres:latest
    container_name: Quiz.Database
    environment:
      - POSTGRES_DB=quiz
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432