services:
  quizapp.api:
    image: ${DOCKER_REGISTRY-}quizappapi
    container_name: QuizApp.Api
    build:
      context: .
      dockerfile: API/QuizApp.API/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081

  quizapp.database:
    image: postgres:latest
    container_name: QuizApp.Database
    environment:
      - POSTGRES_DB=quiz
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  quizapp.identity:
    image: quay.io/keycloak/keycloak:latest
    container_name: QuizApp.Identity
    command: start-dev --import-realm
    environment:
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files:/opt/keycloak/data/import
    ports:
      - 18080:8080

  quizapp.seq:
    image: datalust/seq:latest
    container_name: QuizApp.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80

  quizapp.redis:
    image: redis:latest
    container_name: QuizApp.Redis
    restart: always
    ports:
      - 6379:6379