// <auto-generated>
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Subscriptions.Infrustructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Update_Subscription_Relation : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_subscription_benefits_subscriptions_subscription_id",
                schema: "subscriptions",
                table: "subscription_benefits");

            migrationBuilder.DropIndex(
                name: "ix_subscription_benefits_subscription_id",
                schema: "subscriptions",
                table: "subscription_benefits");

            migrationBuilder.DropColumn(
                name: "subscription_id",
                schema: "subscriptions",
                table: "subscription_benefits");

            migrationBuilder.CreateTable(
                name: "subscription_subscription_benefit",
                schema: "subscriptions",
                columns: table => new
                {
                    subscription_benefits_id = table.Column<Guid>(type: "uuid", nullable: false),
                    subscriptions_id = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_subscription_subscription_benefit", x => new { x.subscription_benefits_id, x.subscriptions_id });
                    table.ForeignKey(
                        name: "fk_subscription_subscription_benefit_subscription_benefits_sub",
                        column: x => x.subscription_benefits_id,
                        principalSchema: "subscriptions",
                        principalTable: "subscription_benefits",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_subscription_subscription_benefit_subscriptions_subscriptio",
                        column: x => x.subscriptions_id,
                        principalSchema: "subscriptions",
                        principalTable: "subscriptions",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_subscription_subscription_benefit_subscriptions_id",
                schema: "subscriptions",
                table: "subscription_subscription_benefit",
                column: "subscriptions_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "subscription_subscription_benefit",
                schema: "subscriptions");

            migrationBuilder.AddColumn<Guid>(
                name: "subscription_id",
                schema: "subscriptions",
                table: "subscription_benefits",
                type: "uuid",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.CreateIndex(
                name: "ix_subscription_benefits_subscription_id",
                schema: "subscriptions",
                table: "subscription_benefits",
                column: "subscription_id");

            migrationBuilder.AddForeignKey(
                name: "fk_subscription_benefits_subscriptions_subscription_id",
                schema: "subscriptions",
                table: "subscription_benefits",
                column: "subscription_id",
                principalSchema: "subscriptions",
                principalTable: "subscriptions",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
