// <auto-generated>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Quiz.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class QuizConfigurationAdded : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "title",
                schema: "quizzes",
                table: "quizzes",
                type: "character varying(255)",
                maxLength: 255,
                nullable: true,
                oldClrType: typeof(string),
                oldType: "text",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "difficulty",
                schema: "quizzes",
                table: "quizzes",
                type: "text",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "integer");

            migrationBuilder.AlterColumn<string>(
                name: "description",
                schema: "quizzes",
                table: "quizzes",
                type: "TEXT",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "text",
                oldNullable: true);

            migrationBuilder.CreateIndex(
                name: "ix_quizzes_quiz_set_id",
                schema: "quizzes",
                table: "quizzes",
                column: "quiz_set_id");

            migrationBuilder.AddForeignKey(
                name: "fk_quizzes_quiz_sets_quiz_set_id",
                schema: "quizzes",
                table: "quizzes",
                column: "quiz_set_id",
                principalSchema: "quizzes",
                principalTable: "quiz_sets",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_quizzes_quiz_sets_quiz_set_id",
                schema: "quizzes",
                table: "quizzes");

            migrationBuilder.DropIndex(
                name: "ix_quizzes_quiz_set_id",
                schema: "quizzes",
                table: "quizzes");

            migrationBuilder.AlterColumn<string>(
                name: "title",
                schema: "quizzes",
                table: "quizzes",
                type: "text",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "character varying(255)",
                oldMaxLength: 255,
                oldNullable: true);

            migrationBuilder.AlterColumn<int>(
                name: "difficulty",
                schema: "quizzes",
                table: "quizzes",
                type: "integer",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "text");

            migrationBuilder.AlterColumn<string>(
                name: "description",
                schema: "quizzes",
                table: "quizzes",
                type: "text",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "TEXT",
                oldNullable: true);
        }
    }
}
